//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSProj2HRL.DbSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StId { get; set; }
        public string LoginId { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string PassWD { get; set; }
        public int SCId { get; set; }
    
        public virtual SchoolClasses SchoolClasses { get; set; }
    }
}
