//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSProj2HRL.DbSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetables
    {
        public int TtId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Lesson1 { get; set; }
        public string Lesson2 { get; set; }
        public string Lesson3 { get; set; }
        public string Lesson4 { get; set; }
    
        public virtual SchoolClasses SchoolClasses { get; set; }
    }
}
